    module.exports = {
        STATUS_503: 503,
        STATUS_500: 500,
        STATUS_400: 400,
        STATUS_401: 401,
        STATUS_404: 404,
        STATUS_409: 409,
        STATUS_426: 426,
        STATUS_200: 200,
        STATUS_201:201,
        STATUS_301: 301,
        STATUS_TRUE: true,
        STATUS_FALSE: false,
        STATUS_MSG_500: "Internal Server Error.",
        STATUS_MSG_400: "Bad Request.",
        STATUS_MSG_404: "Deatils Not Found, Please signup.",
        STATUS_MSG_401: "Oops something went wrong / Unauthorized",
        STATUS_MSG_404_R: "Roles Are Not Found, Please check with db Admin.",
        STATUS_MSG_409: "User Already Existed.",
        STATUS_MSG_426: "Upgrade Required.",
        STATUS_MSG_200: "Success.",
        STATUS_MSG_201: "Created Successfully.",
        STATUS_MSG_201_U: "Updated Successfully.",
        STATUS_MSG_Delete: " Deleted Sucessfully.",
        STATUS_MSG_Update: " Updated Sucessfully.",
        STATUS_MSG_OTPFAIL: "Please Enter valid Otp.",
        DESTINATION_FOLDER:"./uploads"
    };